# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Scripter
version:      0.024
version_from: lib/WWW/Scripter.pm
installdirs:  site
requires:
    Bundle::LWP5_837:              0
    CSS::DOM::Interface:           0
    Encode:                        0
    Exporter:                      5.57
    HTML::DOM:                     0.045
    HTML::DOM::Collection:         0
    HTML::DOM::Element::Form:      0.039
    HTML::DOM::EventTarget:        0.034
    HTML::DOM::Interface:          0.019
    HTML::DOM::NodeList::Magic:    0.02
    HTML::DOM::View:               0.018
    lib:                           0
    List::Util:                    0
    overload:                      0
    Scalar::Util:                  1.09
    strict:                        0
    Test::More:                    0
    Tie::RefHash::Weak:            0.08
    Time::HiRes:                   0
    URI:                           0
    URI::data:                     0
    URI::file:                     0
    utf8:                          0
    warnings:                      0
    WWW::Mechanize:                1.52
    WWW::Mechanize::Image:         0
    WWW::Mechanize::Link:          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
