# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Scripter
version:      0.002
version_from: lib/WWW/Scripter.pm
installdirs:  site
requires:
    Encode:                        0
    Exporter:                      5.57
    Hash::Util::FieldHash::Compat: 0
    HTML::DOM:                     0.021
    HTML::DOM::Collection:         0
    HTML::DOM::EventTarget:        0
    HTML::DOM::Interface:          0.019
    HTML::DOM::NodeList::Magic:    0.02
    HTML::DOM::View:               0.018
    HTTP::Headers::Util:           0
    lib:                           0
    LWP:                           5
    LWP::Protocol:                 0
    LWP::UserAgent:                5.815
    overload:                      0
    Scalar::Util:                  1.09
    strict:                        0
    Test::More:                    0
    URI:                           0
    URI::data:                     0
    URI::file:                     0
    utf8:                          0
    warnings:                      0
    WWW::Mechanize:                1.5
    WWW::Mechanize::Image:         0
    WWW::Mechanize::Link:          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
