--- #YAML:1.0
name:               WWW-Scripter
version:            0.021
abstract:           For scripting web sites that have scripts
author:
    - Father Chrysostomos <sprout at, um, cpan dot org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    CSS::DOM::Interface:  0
    Encode:               0
    Exporter:             5.57
    HTML::DOM:            0.045
    HTML::DOM::Collection:  0
    HTML::DOM::Element::Form:  0.039
    HTML::DOM::EventTarget:  0.034
    HTML::DOM::Interface:  0.019
    HTML::DOM::NodeList::Magic:  0.02
    HTML::DOM::View:      0.018
    HTML::Form:           1.038
    HTML::HeadParser:     0
    HTML::TokeParser:     2.28
    HTML::TreeBuilder:    0
    HTTP::Headers::Util:  0
    HTTP::Message:        1.34
    HTTP::Request:        1.3
    HTTP::Request::Common:  0
    HTTP::Response:       1.35
    lib:                  0
    List::Util:           0
    LWP:                  5
    LWP::Protocol:        0
    LWP::UserAgent:       5.827
    overload:             0
    Scalar::Util:         1.09
    strict:               0
    Test::More:           0
    Time::HiRes:          0
    URI:                  0
    URI::data:            0
    URI::file:            0
    URI::URL:             0
    utf8:                 0
    warnings:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
